package com.group.db.group.model;

import java.io.Serializable;
import lombok.Data;

@Data
public class GoodsWithBLOBs extends Goods implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.parameter_values
     *
     * @mbg.generated
     */
    private String parameterValues;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.specification_items
     *
     * @mbg.generated
     */
    private String specificationItems;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.introduction
     *
     * @mbg.generated
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.product_images
     *
     * @mbg.generated
     */
    private String productImages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}