package com.group.db.group.model;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

@Data
public class GrouponTeam extends GrouponTeamKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupon_team.captain
     *
     * @mbg.generated
     */
    private Short captain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupon_team.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupon_team.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table groupon_team
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}