package com.group.db.group.model;

import java.io.Serializable;
import lombok.Data;

@Data
public class GrouponTeamKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupon_team.groupon_id
     *
     * @mbg.generated
     */
    private String grouponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupon_team.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table groupon_team
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}