package com.group.db.group.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import lombok.Data;

@Data
public class OrderDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.detail_id
     *
     * @mbg.generated
     */
    private String detailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.product_id
     *
     * @mbg.generated
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.product_model
     *
     * @mbg.generated
     */
    private String productModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.product_spec
     *
     * @mbg.generated
     */
    private String productSpec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.group_price
     *
     * @mbg.generated
     */
    private BigDecimal groupPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.product_price
     *
     * @mbg.generated
     */
    private BigDecimal productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.product_quantity
     *
     * @mbg.generated
     */
    private Integer productQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.product_icon
     *
     * @mbg.generated
     */
    private String productIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_detail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}