package com.group.db.group.mapper;

import com.group.db.group.model.Goods;
import com.group.db.group.model.GoodsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    GoodsWithBLOBs selectByPrimaryKey(String sn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    int insertSelective(GoodsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sn);

    List<Goods> selectByCondition(GoodsWithBLOBs record);

    List<Goods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    int deleteBySelective(GoodsWithBLOBs record);
}