package com.group.db.group.mapper;

import com.group.db.group.model.GrouponTeam;
import com.group.db.group.model.GrouponTeamKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface GrouponTeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_team
     *
     * @mbg.generated
     */
    GrouponTeam selectByPrimaryKey(GrouponTeamKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_team
     *
     * @mbg.generated
     */
    int insertSelective(GrouponTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_team
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GrouponTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_team
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(GrouponTeamKey key);

    List<GrouponTeam> selectByCondition(GrouponTeam record);

    List<GrouponTeam> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_team
     *
     * @mbg.generated
     */
    int deleteBySelective(GrouponTeam record);
}