package com.group.db.group.mapper;

import com.group.db.group.model.Groupon;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface GrouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    Groupon selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    int insertSelective(Groupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Groupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    List<Groupon> selectByCondition(Groupon record);

    List<Groupon> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon
     *
     * @mbg.generated
     */
    int deleteBySelective(Groupon record);
}