package com.group.db.group.mapper;

import com.group.db.group.model.OrderMaster;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface OrderMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbg.generated
     */
    OrderMaster selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbg.generated
     */
    int insertSelective(OrderMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String orderId);

    List<OrderMaster> selectByCondition(OrderMaster record);

    List<OrderMaster> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbg.generated
     */
    int deleteBySelective(OrderMaster record);
}