package com.group.db.group.mapper;

import com.group.db.group.model.Sn;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface SnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sn
     *
     * @mbg.generated
     */
    Sn selectByPrimaryKey(Integer type);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sn
     *
     * @mbg.generated
     */
    int insertSelective(Sn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sn
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Sn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sn
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer type);

    List<Sn> selectByCondition(Sn record);

    List<Sn> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sn
     *
     * @mbg.generated
     */
    int deleteBySelective(Sn record);
}