package com.group.db.group.mapper;

import com.group.db.group.model.SysCaptcha;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface SysCaptchaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_captcha
     *
     * @mbg.generated
     */
    SysCaptcha selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_captcha
     *
     * @mbg.generated
     */
    int insertSelective(SysCaptcha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_captcha
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysCaptcha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_captcha
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uuid);

    List<SysCaptcha> selectByCondition(SysCaptcha record);

    List<SysCaptcha> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_captcha
     *
     * @mbg.generated
     */
    int deleteBySelective(SysCaptcha record);
}