package com.group.db.group.mapper;

import com.group.db.group.model.SysOss;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface SysOssMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oss
     *
     * @mbg.generated
     */
    SysOss selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oss
     *
     * @mbg.generated
     */
    int insertSelective(SysOss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oss
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysOss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oss
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    List<SysOss> selectByCondition(SysOss record);

    List<SysOss> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oss
     *
     * @mbg.generated
     */
    int deleteBySelective(SysOss record);
}